// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBo8LDz2LcxS2DXPbC0uL6JwyH5bOIZez0',
    appId: '1:161892024249:web:ac54427370816f0223c068',
    messagingSenderId: '161892024249',
    projectId: 'tugas-ericson',
    authDomain: 'tugas-ericson.firebaseapp.com',
    databaseURL: 'https://tugas-ericson-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'tugas-ericson.firebasestorage.app',
    measurementId: 'G-KQCK5W2592',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCE54lsbQdDytDzodVyIBAprqbLZtqGGPE',
    appId: '1:161892024249:android:ac5e92567c9272fe23c068',
    messagingSenderId: '161892024249',
    projectId: 'tugas-ericson',
    databaseURL: 'https://tugas-ericson-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'tugas-ericson.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBzH3xIlDu43ccl4rHaFn6SdEDb_aoaXdY',
    appId: '1:161892024249:ios:703fdcd31dd252fc23c068',
    messagingSenderId: '161892024249',
    projectId: 'tugas-ericson',
    databaseURL: 'https://tugas-ericson-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'tugas-ericson.firebasestorage.app',
    iosClientId: '161892024249-bodn6vdseoi43hrdeuu43ns12gnk9pg3.apps.googleusercontent.com',
    iosBundleId: 'com.example.tugasEricson',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBzH3xIlDu43ccl4rHaFn6SdEDb_aoaXdY',
    appId: '1:161892024249:ios:703fdcd31dd252fc23c068',
    messagingSenderId: '161892024249',
    projectId: 'tugas-ericson',
    databaseURL: 'https://tugas-ericson-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'tugas-ericson.firebasestorage.app',
    iosClientId: '161892024249-bodn6vdseoi43hrdeuu43ns12gnk9pg3.apps.googleusercontent.com',
    iosBundleId: 'com.example.tugasEricson',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBo8LDz2LcxS2DXPbC0uL6JwyH5bOIZez0',
    appId: '1:161892024249:web:14f811876deea93923c068',
    messagingSenderId: '161892024249',
    projectId: 'tugas-ericson',
    authDomain: 'tugas-ericson.firebaseapp.com',
    databaseURL: 'https://tugas-ericson-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'tugas-ericson.firebasestorage.app',
    measurementId: 'G-M1RGH6FH2T',
  );
}
